# Generated by Django 5.2.8 on 2025-11-28 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avalible',
            new_name='available',
        ),
    ]
